version: 2

jobs:
  build:
    shell: /bin/bash
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm i
      - run:
          command: |
            b=(${CIRCLE_BRANCH/-/ })
            if [ $b == "release" ]; then
              echo "Publishing to NPM"
              npm publish --access=public
            fi

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: org-global
